# Generated by Django 6.0.2 on 2026-02-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_is_inquisitor_alter_customuser_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_inquisitor",
            new_name="is_inspector",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_first_login",
            field=models.BooleanField(default=False),
        ),
    ]
