# Generated by Django 6.0.2 on 2026-03-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_rename_is_inquisitor_customuser_is_inspector_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_first_login',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('1', 'ordinary mason'), ('2', 'silver mason'), ('3', 'gold mason'), ('4', 'architect')], default='1', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('role', '4')), fields=('role',), name='unique_architect_in_system'),
        ),
    ]
